repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-format
        name: "Ruff Formatter"
        stages: [pre-commit]

      - id: ruff
        name: "Ruff Linter"
        stages: [pre-commit]
        args: [--fix, --exit-zero]