[project]
name = "metadata-ingestion"
version = "0.1.0"
description = "Metadata ingestion package with factory pattern to ingest data to delta lake from diverse sources."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "commitizen>=4.2.2,<5",
    "ruff>=0.9.7,<0.13",
    "pre-commit<5"
]
